### ISSUE TITLE
does not compile under gcc 6.3

### ISSUE THREAD

**Issue by scruss** [zub2/dotprint#1]
changing `src/CMakeLists.txt` from

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++98 -Wall -Wextra -pedantic ${DEPS_CFLAGS_OTHER}")

to

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wextra -pedantic ${DEPS_CFLAGS_OTHER}")

allows the code to compile.

**Comment by zub2** [comment]
Thanks for the report. The cause seems to be that libsigc++ >=2.5.1 requires C++11. libsigc++ is used by gtkmm, which is used by dotprint.

**Comment by zub2** [comment]
@scruss Ouch, I didn't mean to say "WON'TFIX". I just described the cause. The issue should be fixed now.

**Comment by scruss** [comment]
sorry, didn't mean for you to think I didn't think you'd fix the problem - quite the opposite! I closed the issue 'cos you'd responded and affirmed it, so I thought you'd probably want to patch it in your own time without an issue hanging over your head. I guess I have much to learn about issue etiquette …
